### ISSUE TITLE
Support migration interfaces should explicit extend MigrationInterface

### ISSUE THREAD

**Issue by andrew-demb** [gruberro/php-mongo-migrations#20]
I think `ContextualMigrationInterface` and `RunAlwaysMigrationInterface` should extend `MigrationInterface` because without it they are useless.

What do you think?

**Comment by gruberro** [comment]
@andrew-demb thats probably a good idea. Makes the interface usage much clearer. Tried your approach in #21. Could you please take a look if this is how you intended the changes? IMHO this also introduces no BC issues!

**Comment by andrew-demb** [comment]
> IMHO this also introduces no BC issues!

Yes, I think so. These interfaces should not be used in another way.
